package errors

const (
	//video
	ERR_VIDEO_NOT_FOUND AppErrorType = iota
	ERR_VIDEO_INFO
	ERR_VIDEO_SEEK
	ERR_VIDEO_SEND

	// user
	ERR_USER_NOT_FOUND
	ERR_EMAIL_ALREADY_EXISTS
	ERR_INVALID_CREDENTIALS

	//global
	ERR_VALIDATION_FAILED
	ERR_INTERNAL_SERVER_ERROR
)
